name: deploy_firebase

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.2.2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7.9.5
          run_install: false
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-key: |
            ${{ runner.os }}-pnpm-store-
      - name: Install Dependencies
        run: pnpm install
      - name: Create .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_BOBO_API_KEY: '${{ secrets.API_KEY }}'
          envkey_BOBO_AUTH_DOMAIN: '${{ secrets.AUTH_DOMAIN }}'
          envkey_BOBO_DATABASE_URL: '${{ secrets.DATABASE_URL }}'
          envkey_BOBO_APP_ID: '${{ secrets.APP_ID }}'
          envkey_BOBO_PROJECT_ID: '${{ secrets.PROJECT_ID }}'
          envkey_BOBO_STORAGE_BUCKET: '${{ secrets.STORAGE_BUCKET }}'
          envkey_BOBO_MESSAGING_SENDER_ID: '${{ secrets.MESSAGING_SENDER_ID }}'
      - name: Verify .env
        run: cat .env
      - name: Build
        run: pnpm build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THEFLIES_CFF90 }}'
          projectId: theflies-cff90
          channelID: live
  #     - name: Archive Production Artifact
  #       uses: actions/upload-artifact@master
  #       with:
  #         name: dist
  #         path: dist
  # deploy:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@master
  #     - name: Download Artifact
  #       uses: actions/download-artifact@master
  #       with:
  #         name: dist
  #         path: dist
  #     - name: Deploy to Firebase
  #       uses: FirebaseExtended/action-hosting-deploy@v0
  #       with:
  #         repoToken: '${{ secrets.GITHUB_TOKEN }}'
  #         firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_THEFLIES_CFF90 }}'
  #         projectId: theflies-cff90
